Провалидиируем результаты

In [1]:
%load_ext sql
%sql postgresql://postgres:postgres@localhost:5432/postgres

In [9]:
%%sql
-- Объём данных
SELECT
    (SELECT COUNT(*) FROM mock_data) AS source_rows,
    (SELECT COUNT(*) FROM fact_sale) AS fact_rows,
    (SELECT COUNT(*) FROM dim_product) AS products;

   source_rows  fact_rows  products
0        10000      10000     10000

In [10]:
%%sql
-- Висячие ссылки в факте
SELECT
    COUNT(*) FILTER (WHERE sale_customer_id IS NULL) AS missing_customers,
    COUNT(*) FILTER (WHERE sale_seller_id IS NULL) AS missing_seller,
    COUNT(*) FILTER (WHERE sale_product_id IS NULL) AS missing_products,
    COUNT(*) FILTER (WHERE sale_supplier_id IS NULL) AS missing_suppliers,
    COUNT(*) FILTER (WHERE sale_store_id IS NULL) AS missing_stores,
    COUNT(*) FILTER (WHERE sale_category_id IS NULL) AS missing_categories
FROM fact_sale;

,missing_customers,missing_seller,missing_products,missing_suppliers,missing_stores,missing_categories
0,0,0,0,0,0,0